version: '3.4'

services:
  server:
    image: jewelry-shop
    container_name: "jewelry-shop"
    build: ./
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PAYMENT_API_KEY=${PAYMENT_API_KEY}
      - PAYMENT_API_SECRET=${PAYMENT_API_SECRET}
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 55432:5432