version: '3.4'

services:
  server:
    image: jewelry-shop
    container_name: "jewelry-shop"
    build: ./
    command: ./app
    environment:
      - "STORAGE_ACCESS_KEY=minioadmin"
      - "STORAGE_SECRET=minioadmin"
    ports:
      - 8000:8000
    depends_on:
      - db
      - storage

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 55432:5432

  storage:
      restart: always
      image: minio/minio
      ports:
        - 9000:9000
      volumes:
        - ./.build/volumes/storages/minio:/data
      environment:
        MINIO_ACCESS_KEY: minioadmin
        MINIO_SECRET_KEY: minioadmin
      command: minio server /minio/data
