version: '3.4'

services:
  server:
    image: jewelry-shop
    container_name: "jewelry-shop"
    build: ./
    command: ./app
    environment:
      - "STORAGE_ACCESS_KEY=admin"
      - "STORAGE_SECRET=secret"
    ports:
      - 8000:8000
    depends_on:
      - db
      - localstack

  db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - ./.build/volumes/databases/postgres/data:/var/lib/postgresql/data
    ports:
      - 55432:5432

  localstack:
    image: localstack/localstack:latest
    container_name: "localstack"
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'