port: 8000

auth:
  hash_salt: "PIxP1o559vv5SQGiOEat"
  signing_key: "PIxP1o559vv5SQGiOEat"

db:
  postgres:
    username: "postgres"
    dbname: "postgres"
    sslmode: "disable"
    port: "5432"
    host: "db"

storage:
  url: "ams3.digitaloceanspaces.com"
  bucket: "jewerly"

payments:
  endpoint: "https://preprod.paymeservice.com/api/"
  callback_url: "http://35f1ca80bb87.ngrok.io/payment/callback"
  return_url: "https://www.example.com/payment/success"

email:
  smtp:
    sender: "info@silverrain-jewelry.com"
    host: "mail.your-server.de"
    port: ":25"