db:
  postgres:
    dbname: "stage"

payments:
  callback_url: "http://silverrain-jewelry.com:8001/payment/callback"
  return_url: "http://silverrain-jewelry.com:8080/status-page.html"


email:
  support:
    email: "support-stage@silverrain-jewelry.com"
    name: "Silver Rain Support"
  sender:
    email: "info-stage@silverrain-jewelry.com"
    name: "Silver Rain Info"